-- Willow Talk Edition - Generated Prompts
-- Generated on: 2025-10-11T17:13:52.287Z
-- Total prompts: 485

-- Clear existing prompts
DELETE FROM prompts;

-- Insert all prompts
INSERT INTO prompts (prompt_text, tier, category, difficulty, is_premium_only) VALUES
('What''s the most unexpected thing you did at a hangout that surprised everyone?', 'spark', 'squad', 'easy', false),
('What''s something you thought was normal until you realized no one else does it?', 'spark', 'squad', 'easy', false),
('What''s the weirdest thing you''ve ever googled at 3 AM?', 'spark', 'squad', 'easy', false),
('What''s a habit you have that you''re pretty sure is unique to you?', 'spark', 'squad', 'easy', false),
('What''s the most random thing you''ve ever impulse-bought?', 'spark', 'squad', 'easy', false),
('What''s something you do when you''re alone that would be weird if people saw?', 'spark', 'squad', 'easy', false),
('What''s the strangest compliment you''ve ever received?', 'spark', 'squad', 'easy', false),
('What''s a food combination you love that others find disgusting?', 'spark', 'squad', 'easy', false),
('What''s the most embarrassing autocorrect fail you''ve ever sent?', 'spark', 'squad', 'easy', false),
('What''s something you''re secretly really good at that no one knows about?', 'spark', 'squad', 'easy', false),
('What''s the weirdest dream you''ve had that you still remember?', 'spark', 'squad', 'easy', false),
('What''s a childhood fear you had that makes no sense now?', 'spark', 'squad', 'easy', false),
('What''s the most ridiculous thing you''ve ever cried about?', 'spark', 'squad', 'easy', false),
('What''s something you used to believe as a kid that was completely wrong?', 'spark', 'squad', 'easy', false),
('What''s the most awkward social situation you''ve ever been in?', 'spark', 'squad', 'easy', false),
('What''s a skill you wish you had but have never tried to learn?', 'spark', 'squad', 'easy', false),
('What''s the weirdest thing you''ve ever found in your room?', 'spark', 'squad', 'easy', false),
('What''s something you do differently than everyone else you know?', 'spark', 'squad', 'easy', false),
('What''s the most random fact you know that serves no purpose?', 'spark', 'squad', 'easy', false),
('What''s a weird talent you have that you''re oddly proud of?', 'spark', 'squad', 'easy', false),
('What''s the strangest way you''ve ever met someone?', 'spark', 'squad', 'easy', false),
('What''s something you''ve always wanted to try but never had the courage?', 'spark', 'squad', 'easy', false),
('What''s the most embarrassing thing you''ve ever done for attention?', 'spark', 'squad', 'easy', false),
('What''s a weird superstition you have that you know is silly?', 'spark', 'squad', 'easy', false),
('What''s the most unexpected way you''ve ever made someone laugh?', 'spark', 'squad', 'easy', false),
('What''s something you''re working on improving about yourself right now?', 'vibe', 'squad', 'medium', false),
('What''s a goal you have that you haven''t told many people about?', 'vibe', 'squad', 'medium', false),
('What''s something you''ve learned about yourself recently?', 'vibe', 'squad', 'medium', false),
('What''s a challenge you''re facing that you could use support with?', 'vibe', 'squad', 'medium', false),
('What''s something you''re proud of that you don''t usually talk about?', 'vibe', 'squad', 'medium', false),
('What''s a belief or value that''s really important to you?', 'vibe', 'squad', 'medium', false),
('What''s something you''ve changed your mind about recently?', 'vibe', 'squad', 'medium', false),
('What''s a way you''ve grown or changed in the past year?', 'vibe', 'squad', 'medium', false),
('What''s something you''re curious about that you''ve never explored?', 'vibe', 'squad', 'medium', false),
('What''s a fear you have that you''re working to overcome?', 'vibe', 'squad', 'medium', false),
('What''s something you''ve discovered about yourself through friendship?', 'vibe', 'squad', 'medium', false),
('What''s a way you''ve helped someone that made you feel good?', 'vibe', 'squad', 'medium', false),
('What''s something you''re grateful for that you don''t usually mention?', 'vibe', 'squad', 'medium', false),
('What''s a lesson you''ve learned from a difficult experience?', 'vibe', 'squad', 'medium', false),
('What''s something you wish you could tell your younger self?', 'vibe', 'squad', 'medium', false),
('What''s a way you''ve surprised yourself recently?', 'vibe', 'squad', 'medium', false),
('What''s something you''re looking forward to that excites you?', 'vibe', 'squad', 'medium', false),
('What''s a quality you admire in others that you''re trying to develop?', 'vibe', 'squad', 'medium', false),
('What''s something you''ve realized about what makes you happy?', 'vibe', 'squad', 'medium', false),
('What''s a way you''ve become more confident recently?', 'vibe', 'squad', 'medium', false),
('What''s something you''ve learned about friendship that changed your perspective?', 'vibe', 'squad', 'medium', false),
('What''s a challenge you''ve overcome that made you stronger?', 'vibe', 'squad', 'medium', false),
('What''s something you''re working on that requires patience?', 'vibe', 'squad', 'medium', false),
('What''s a way you''ve become more understanding of others?', 'vibe', 'squad', 'medium', false),
('What''s something you''ve discovered about yourself that surprised you?', 'vibe', 'squad', 'medium', false),
('What''s the most important thing you''ve learned about friendship?', 'lockin', 'squad', 'hard', false),
('What''s something you''ve never told anyone that you think people would understand?', 'lockin', 'squad', 'hard', false),
('What''s your biggest fear about losing important relationships?', 'lockin', 'squad', 'hard', false),
('What''s the most meaningful way someone has supported you?', 'lockin', 'squad', 'hard', false),
('What''s something you want to change about how you connect with others?', 'lockin', 'squad', 'hard', false),
('What''s your vision for your relationships in 10 years?', 'lockin', 'squad', 'hard', false),
('What''s something you''d never want to lose about your closest friendships?', 'lockin', 'squad', 'hard', false),
('What''s the hardest thing you''ve had to forgive someone for?', 'lockin', 'squad', 'hard', false),
('If you could relive one memory but change one thing, what would it be?', 'lockin', 'squad', 'hard', false),
('What''s the most vulnerable thing you''ve never told anyone?', 'lockin', 'squad', 'hard', false),
('What''s a way you''ve helped someone through their darkest time?', 'lockin', 'squad', 'hard', false),
('What''s something you''ve learned about yourself through deep friendship?', 'lockin', 'squad', 'hard', false),
('What''s a way you''ve changed because of meaningful relationships?', 'lockin', 'squad', 'hard', false),
('What''s something you''re grateful for about your friendships that you don''t usually say?', 'lockin', 'squad', 'hard', false),
('What''s a challenge you''ve overcome together that made you stronger?', 'lockin', 'squad', 'hard', false),
('What''s your favorite thing about how you handle disagreements with friends?', 'lockin', 'squad', 'hard', false),
('What''s something you''ve learned about yourself through supporting others?', 'lockin', 'squad', 'hard', false),
('What''s a way you''ve helped someone through a tough time?', 'lockin', 'squad', 'hard', false),
('What''s something you''re grateful for about your friendships that you don''t usually say?', 'lockin', 'squad', 'hard', false),
('What''s a challenge you''ve overcome together that made you stronger?', 'lockin', 'squad', 'hard', false),
('What''s your favorite thing about how you handle disagreements with friends?', 'lockin', 'squad', 'hard', false),
('What''s something you''ve learned about yourself through supporting others?', 'lockin', 'squad', 'hard', false),
('What''s a way you''ve helped someone through a tough time?', 'lockin', 'squad', 'hard', false),
('What''s something you''re grateful for about your friendships that you don''t usually say?', 'lockin', 'squad', 'hard', false),
('What''s a challenge you''ve overcome together that made you stronger?', 'lockin', 'squad', 'hard', false),
('What''s something about yourself that you think I don''t know yet?', 'spark', 'ride-or-die', 'easy', false),
('What''s a childhood memory that shaped who you are today?', 'spark', 'ride-or-die', 'easy', false),
('What''s something you''re secretly really good at that might surprise me?', 'spark', 'ride-or-die', 'easy', false),
('What''s a fear or insecurity you have that you haven''t shared with me?', 'spark', 'ride-or-die', 'easy', false),
('What''s something you''ve always wanted to try but never had the courage to do?', 'spark', 'ride-or-die', 'easy', false),
('What''s a belief or value that''s really important to you that I might not know about?', 'spark', 'ride-or-die', 'easy', false),
('What''s something you''re proud of that you''ve never told me about?', 'spark', 'ride-or-die', 'easy', false),
('What''s a way you''ve changed or grown recently that you want me to notice?', 'spark', 'ride-or-die', 'easy', false),
('What''s something you''re curious about me that you''ve never asked?', 'spark', 'ride-or-die', 'easy', false),
('What''s a dream or goal you have that you haven''t shared with me yet?', 'spark', 'ride-or-die', 'easy', false),
('What''s something you wish you could tell your past self about relationships?', 'spark', 'ride-or-die', 'easy', false),
('What''s a way you show love or care that you think I might not notice?', 'spark', 'ride-or-die', 'easy', false),
('What''s something you''re working on improving about yourself right now?', 'spark', 'ride-or-die', 'easy', false),
('What''s a quality you admire in others that you wish you had more of?', 'spark', 'ride-or-die', 'easy', false),
('What''s something you''re grateful for that you don''t usually talk about?', 'spark', 'ride-or-die', 'easy', false),
('What''s a quirky habit of mine you secretly love?', 'spark', 'ride-or-die', 'easy', false),
('What''s something about me that surprised you when we first met?', 'spark', 'ride-or-die', 'easy', false),
('What''s a small thing I do that makes you smile?', 'spark', 'ride-or-die', 'easy', false),
('What''s something you''ve learned about yourself since we''ve been together?', 'spark', 'ride-or-die', 'easy', false),
('What''s a memory of us that you think about often?', 'spark', 'ride-or-die', 'easy', false),
('What''s something you''re curious about my past that you''ve never asked?', 'spark', 'ride-or-die', 'easy', false),
('What''s a way I make you feel most loved?', 'spark', 'ride-or-die', 'easy', false),
('What''s something you''ve always wanted to tell me but haven''t found the right moment?', 'spark', 'ride-or-die', 'easy', false),
('What''s a dream you have for us that you haven''t shared yet?', 'spark', 'ride-or-die', 'easy', false),
('What''s something about our relationship that makes you feel most secure?', 'spark', 'ride-or-die', 'easy', false),
('What''s a small habit of mine that makes you smile?', 'vibe', 'ride-or-die', 'medium', false),
('What''s your favorite memory of us together?', 'vibe', 'ride-or-die', 'medium', false),
('What''s something you''ve always wanted to tell me but haven''t?', 'vibe', 'ride-or-die', 'medium', false),
('What''s your love language and how do you show it?', 'vibe', 'ride-or-die', 'medium', false),
('What''s the most vulnerable thing you''ve shared with me?', 'vibe', 'ride-or-die', 'medium', false),
('What''s something about me that surprised you when we first met?', 'vibe', 'ride-or-die', 'medium', false),
('What''s a way I make you feel most loved?', 'vibe', 'ride-or-die', 'medium', false),
('What''s something you''ve learned about yourself through our relationship?', 'vibe', 'ride-or-die', 'medium', false),
('If we could swap one daily routine, what would you want to try from my life?', 'vibe', 'ride-or-die', 'medium', false),
('What''s a challenge we''ve overcome together that made us stronger?', 'vibe', 'ride-or-die', 'medium', false),
('What''s your favorite thing about how we handle disagreements?', 'vibe', 'ride-or-die', 'medium', false),
('What''s something you''ve learned about yourself through our relationship?', 'vibe', 'ride-or-die', 'medium', false),
('What''s a way I''ve helped you heal from past wounds?', 'vibe', 'ride-or-die', 'medium', false),
('What''s something about our relationship that scares you?', 'vibe', 'ride-or-die', 'medium', false),
('What''s the most important thing you''ve learned about love from being with me?', 'vibe', 'ride-or-die', 'medium', false),
('What''s a way you''ve changed because of our relationship?', 'vibe', 'ride-or-die', 'medium', false),
('What''s something you''re grateful for about our relationship that you don''t usually say?', 'vibe', 'ride-or-die', 'medium', false),
('What''s a challenge we''ve overcome together that made us stronger?', 'vibe', 'ride-or-die', 'medium', false),
('What''s your favorite thing about how we handle disagreements?', 'vibe', 'ride-or-die', 'medium', false),
('What''s something you''ve learned about yourself through our relationship?', 'vibe', 'ride-or-die', 'medium', false),
('What''s a way I''ve helped you heal from past wounds?', 'vibe', 'ride-or-die', 'medium', false),
('What''s something about our relationship that scares you?', 'vibe', 'ride-or-die', 'medium', false),
('What''s the most important thing you''ve learned about love from being with me?', 'vibe', 'ride-or-die', 'medium', false),
('What''s a way you''ve changed because of our relationship?', 'vibe', 'ride-or-die', 'medium', false),
('What''s something you''re grateful for about our relationship that you don''t usually say?', 'vibe', 'ride-or-die', 'medium', false),
('What''s our biggest shared dream?', 'lockin', 'ride-or-die', 'hard', false),
('What''s the most vulnerable thing you''ve ever shared with me?', 'lockin', 'ride-or-die', 'hard', false),
('What''s something you want to change about our relationship?', 'lockin', 'ride-or-die', 'hard', false),
('What''s your deepest fear about our future together?', 'lockin', 'ride-or-die', 'hard', false),
('What''s the most important lesson you''ve learned from our relationship?', 'lockin', 'ride-or-die', 'hard', false),
('What''s your vision for our life together in 10 years?', 'lockin', 'ride-or-die', 'hard', false),
('What''s something you''d never want to lose about our connection?', 'lockin', 'ride-or-die', 'hard', false),
('What''s the hardest thing you''ve had to forgive me for?', 'lockin', 'ride-or-die', 'hard', false),
('What''s a dream we''ve never shared that could change our future together?', 'lockin', 'ride-or-die', 'hard', false),
('What''s the most difficult conversation we''ve ever had and what did it teach us?', 'lockin', 'ride-or-die', 'hard', false),
('What''s a way I''ve helped you heal from past wounds?', 'lockin', 'ride-or-die', 'hard', false),
('What''s your deepest insecurity and how can I help you overcome it?', 'lockin', 'ride-or-die', 'hard', false),
('What''s something about our relationship that scares you?', 'lockin', 'ride-or-die', 'hard', false),
('What''s the most important thing you''ve learned about love from being with me?', 'lockin', 'ride-or-die', 'hard', false),
('What''s a way you''ve changed because of our relationship?', 'lockin', 'ride-or-die', 'hard', false),
('What''s something you''re grateful for about our relationship that you don''t usually say?', 'lockin', 'ride-or-die', 'hard', false),
('What''s a challenge we''ve overcome together that made us stronger?', 'lockin', 'ride-or-die', 'hard', false),
('What''s your favorite thing about how we handle disagreements?', 'lockin', 'ride-or-die', 'hard', false),
('What''s something you''ve learned about yourself through our relationship?', 'lockin', 'ride-or-die', 'hard', false),
('What''s a way I''ve helped you heal from past wounds?', 'lockin', 'ride-or-die', 'hard', false),
('What''s something about our relationship that scares you?', 'lockin', 'ride-or-die', 'hard', false),
('What''s the most important thing you''ve learned about love from being with me?', 'lockin', 'ride-or-die', 'hard', false),
('What''s a way you''ve changed because of our relationship?', 'lockin', 'ride-or-die', 'hard', false),
('What''s something you''re grateful for about our relationship that you don''t usually say?', 'lockin', 'ride-or-die', 'hard', false),
('What''s a challenge we''ve overcome together that made us stronger?', 'lockin', 'ride-or-die', 'hard', false),
('What''s the moment you knew you wanted to spend the rest of your life with me?', 'spark', 'ride-or-die', 'easy', true),
('If you could change one thing about how we handle conflict, what would it be?', 'spark', 'ride-or-die', 'easy', true),
('What''s the biggest fear you have about our future together?', 'spark', 'ride-or-die', 'easy', true),
('If we had to describe our love in three words, what would yours be?', 'spark', 'ride-or-die', 'easy', true),
('What''s the deepest truth about yourself that you''ve never shared with anyone?', 'spark', 'ride-or-die', 'easy', true),
('Tell me about a quirky habit of mine you secretly love?', 'spark', 'ride-or-die', 'easy', true),
('Tell me about something about me that surprised you when we first met?', 'spark', 'ride-or-die', 'easy', true),
('Tell me about a small thing I do that makes you smile?', 'spark', 'ride-or-die', 'easy', true),
('Tell me about something you''ve learned about yourself since we''ve been together?', 'spark', 'ride-or-die', 'easy', true),
('Tell me about a memory of us that you think about often?', 'spark', 'ride-or-die', 'easy', true),
('Tell me about something you''re curious about my past that you''ve never asked?', 'spark', 'ride-or-die', 'easy', true),
('Tell me about a way I make you feel most loved?', 'spark', 'ride-or-die', 'easy', true),
('Tell me about something you''ve always wanted to tell me but haven''t found the right moment?', 'spark', 'ride-or-die', 'easy', true),
('Tell me about a dream you have for us that you haven''t shared yet?', 'spark', 'ride-or-die', 'easy', true),
('Tell me about something about our relationship that makes you feel most secure?', 'spark', 'ride-or-die', 'easy', true),
('Tell me about a way you show love or care that you think I might not notice?', 'spark', 'ride-or-die', 'easy', true),
('Tell me about something you''re working on improving about yourself right now?', 'spark', 'ride-or-die', 'easy', true),
('Tell me about a quality you admire in others that you wish you had more of?', 'spark', 'ride-or-die', 'easy', true),
('Tell me about something you''re grateful for that you don''t usually talk about?', 'spark', 'ride-or-die', 'easy', true),
('Tell me about a childhood memory that shaped who you are today?', 'spark', 'ride-or-die', 'easy', true),
('Tell me about something you''re secretly really good at that might surprise me?', 'spark', 'ride-or-die', 'easy', true),
('Tell me about a fear or insecurity you have that you haven''t shared with me?', 'spark', 'ride-or-die', 'easy', true),
('Tell me about something you''ve always wanted to try but never had the courage to do?', 'spark', 'ride-or-die', 'easy', true),
('Tell me about a belief or value that''s really important to you that I might not know about?', 'spark', 'ride-or-die', 'easy', true),
('Tell me about something you''re proud of that you''ve never told me about?', 'spark', 'ride-or-die', 'easy', true),
('Tell me about the moment you knew you wanted to spend the rest of your life with me?', 'spark', 'ride-or-die', 'easy', true),
('If we could change one thing about how we handle conflict, what would it be?', 'spark', 'ride-or-die', 'easy', true),
('Tell me about the biggest fear you have about our future together?', 'spark', 'ride-or-die', 'easy', true),
('If we had to describe our love in three words, what would wers be?', 'spark', 'ride-or-die', 'easy', true),
('Tell me about the deepest truth about yourself that you''ve never shared with anyone?', 'spark', 'ride-or-die', 'easy', true),
('Describe a quirky habit of mine you secretly love?', 'spark', 'ride-or-die', 'easy', true),
('Describe something about me that surprised you when we first met?', 'spark', 'ride-or-die', 'easy', true),
('Describe a small thing I do that makes you smile?', 'spark', 'ride-or-die', 'easy', true),
('Describe something you''ve learned about yourself since we''ve been together?', 'spark', 'ride-or-die', 'easy', true),
('Describe a memory of us that you think about often?', 'spark', 'ride-or-die', 'easy', true),
('Describe something you''re curious about my past that you''ve never asked?', 'spark', 'ride-or-die', 'easy', true),
('Describe a way I make you feel most loved?', 'spark', 'ride-or-die', 'easy', true),
('Describe something you''ve always wanted to tell me but haven''t found the right moment?', 'spark', 'ride-or-die', 'easy', true),
('Describe a dream you have for us that you haven''t shared yet?', 'spark', 'ride-or-die', 'easy', true),
('Describe something about our relationship that makes you feel most secure?', 'spark', 'ride-or-die', 'easy', true),
('Describe a way you show love or care that you think I might not notice?', 'spark', 'ride-or-die', 'easy', true),
('Describe something you''re working on improving about yourself right now?', 'spark', 'ride-or-die', 'easy', true),
('Describe a quality you admire in others that you wish you had more of?', 'spark', 'ride-or-die', 'easy', true),
('Describe something you''re grateful for that you don''t usually talk about?', 'spark', 'ride-or-die', 'easy', true),
('Describe a childhood memory that shaped who you are today?', 'spark', 'ride-or-die', 'easy', true),
('Describe something you''re secretly really good at that might surprise me?', 'spark', 'ride-or-die', 'easy', true),
('Describe a fear or insecurity you have that you haven''t shared with me?', 'spark', 'ride-or-die', 'easy', true),
('Describe something you''ve always wanted to try but never had the courage to do?', 'spark', 'ride-or-die', 'easy', true),
('Describe a belief or value that''s really important to you that I might not know about?', 'spark', 'ride-or-die', 'easy', true),
('Describe something you''re proud of that you''ve never told me about?', 'spark', 'ride-or-die', 'easy', true),
('Describe the moment you knew you wanted to spend the rest of your life with me?', 'spark', 'ride-or-die', 'easy', true),
('If you could change one thing about how we handle conflict, what would it be? and why does it matter to you?', 'spark', 'ride-or-die', 'easy', true),
('Describe the biggest fear you have about our future together?', 'spark', 'ride-or-die', 'easy', true),
('If we had to describe our love in three words, what would yours be? and why does it matter to you?', 'spark', 'ride-or-die', 'easy', true),
('Describe the deepest truth about yourself that you''ve never shared with anyone?', 'spark', 'ride-or-die', 'easy', true),
('Share a quirky habit of mine you secretly love?', 'spark', 'ride-or-die', 'easy', true),
('Share something about me that surprised you when we first met?', 'spark', 'ride-or-die', 'easy', true),
('Share a small thing I do that makes you smile?', 'spark', 'ride-or-die', 'easy', true),
('Share something you''ve learned about yourself since we''ve been together?', 'spark', 'ride-or-die', 'easy', true),
('Share a memory of us that you think about often?', 'spark', 'ride-or-die', 'easy', true),
('Share something you''re curious about my past that you''ve never asked?', 'spark', 'ride-or-die', 'easy', true),
('Share a way I make you feel most loved?', 'spark', 'ride-or-die', 'easy', true),
('Share something you''ve always wanted to tell me but haven''t found the right moment?', 'spark', 'ride-or-die', 'easy', true),
('Share a dream you have for us that you haven''t shared yet?', 'spark', 'ride-or-die', 'easy', true),
('Share something about our relationship that makes you feel most secure?', 'spark', 'ride-or-die', 'easy', true),
('Share a way you show love or care that you think I might not notice?', 'spark', 'ride-or-die', 'easy', true),
('Share something you''re working on improving about yourself right now?', 'spark', 'ride-or-die', 'easy', true),
('Share a quality you admire in others that you wish you had more of?', 'spark', 'ride-or-die', 'easy', true),
('Share something you''re grateful for that you don''t usually talk about?', 'spark', 'ride-or-die', 'easy', true),
('Share a childhood memory that shaped who you are today?', 'spark', 'ride-or-die', 'easy', true),
('Share something you''re secretly really good at that might surprise me?', 'spark', 'ride-or-die', 'easy', true),
('Share a fear or insecurity you have that you haven''t shared with me?', 'spark', 'ride-or-die', 'easy', true),
('Share something you''ve always wanted to try but never had the courage to do?', 'spark', 'ride-or-die', 'easy', true),
('Share a belief or value that''s really important to you that I might not know about?', 'spark', 'ride-or-die', 'easy', true),
('Share something you''re proud of that you''ve never told me about?', 'spark', 'ride-or-die', 'easy', true),
('Share the moment you knew you wanted to spend the rest of your life with me?', 'spark', 'ride-or-die', 'easy', true),
('If you could change one thing about how we handle conflict, what would it be? and what makes it special?', 'spark', 'ride-or-die', 'easy', true),
('Share the biggest fear you have about our future together?', 'spark', 'ride-or-die', 'easy', true),
('If we had to describe our love in three words, what would yours be? and what makes it special?', 'spark', 'ride-or-die', 'easy', true),
('Share the deepest truth about yourself that you''ve never shared with anyone?', 'spark', 'ride-or-die', 'easy', true),
('Explain a quirky habit of mine you secretly love?', 'spark', 'ride-or-die', 'easy', true),
('Explain something about me that surprised you when we first met?', 'spark', 'ride-or-die', 'easy', true),
('Explain a small thing I do that makes you smile?', 'spark', 'ride-or-die', 'easy', true),
('Explain something you''ve learned about yourself since we''ve been together?', 'spark', 'ride-or-die', 'easy', true),
('Explain a memory of us that you think about often?', 'spark', 'ride-or-die', 'easy', true),
('Explain something you''re curious about my past that you''ve never asked?', 'spark', 'ride-or-die', 'easy', true),
('Explain a way I make you feel most loved?', 'spark', 'ride-or-die', 'easy', true),
('Explain something you''ve always wanted to tell me but haven''t found the right moment?', 'spark', 'ride-or-die', 'easy', true),
('Explain a dream you have for us that you haven''t shared yet?', 'spark', 'ride-or-die', 'easy', true),
('Explain something about our relationship that makes you feel most secure?', 'spark', 'ride-or-die', 'easy', true),
('Explain a way you show love or care that you think I might not notice?', 'spark', 'ride-or-die', 'easy', true),
('Explain something you''re working on improving about yourself right now?', 'spark', 'ride-or-die', 'easy', true),
('Explain a quality you admire in others that you wish you had more of?', 'spark', 'ride-or-die', 'easy', true),
('Explain something you''re grateful for that you don''t usually talk about?', 'spark', 'ride-or-die', 'easy', true),
('Explain a childhood memory that shaped who you are today?', 'spark', 'ride-or-die', 'easy', true),
('Explain something you''re secretly really good at that might surprise me?', 'spark', 'ride-or-die', 'easy', true),
('Explain a fear or insecurity you have that you haven''t shared with me?', 'spark', 'ride-or-die', 'easy', true),
('Explain something you''ve always wanted to try but never had the courage to do?', 'spark', 'ride-or-die', 'easy', true),
('Explain a belief or value that''s really important to you that I might not know about?', 'spark', 'ride-or-die', 'easy', true),
('Explain something you''re proud of that you''ve never told me about?', 'spark', 'ride-or-die', 'easy', true),
('Explain the moment you knew you wanted to spend the rest of your life with me?', 'spark', 'ride-or-die', 'easy', true),
('If you could change one thing about how we handle conflict, what would it be? and how does it make you feel?', 'spark', 'ride-or-die', 'easy', true),
('Explain the biggest fear you have about our future together?', 'spark', 'ride-or-die', 'easy', true),
('If we had to describe our love in three words, what would yours be? and how does it make you feel?', 'spark', 'ride-or-die', 'easy', true),
('Explain the deepest truth about yourself that you''ve never shared with anyone?', 'spark', 'ride-or-die', 'easy', true),
('Reflect on a quirky habit of mine you secretly love?', 'spark', 'ride-or-die', 'easy', true),
('Reflect on something about me that surprised you when we first met?', 'spark', 'ride-or-die', 'easy', true),
('Reflect on a small thing I do that makes you smile?', 'spark', 'ride-or-die', 'easy', true),
('Reflect on something you''ve learned about yourself since we''ve been together?', 'spark', 'ride-or-die', 'easy', true),
('Reflect on a memory of us that you think about often?', 'spark', 'ride-or-die', 'easy', true),
('Reflect on something you''re curious about my past that you''ve never asked?', 'spark', 'ride-or-die', 'easy', true),
('Reflect on a way I make you feel most loved?', 'spark', 'ride-or-die', 'easy', true),
('Tell me about the most vulnerable thing you''ve shared with me?', 'vibe', 'ride-or-die', 'medium', true),
('Tell me about your love language and how do you show it?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something about me that surprised we when we first met?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a way I make we feel most loved?', 'vibe', 'ride-or-die', 'medium', true),
('Tell me about something you''ve learned about yourself through our relationship?', 'vibe', 'ride-or-die', 'medium', true),
('Tell me about your favorite memory of us together?', 'vibe', 'ride-or-die', 'medium', true),
('Tell me about something you''ve always wanted to tell me but haven''t?', 'vibe', 'ride-or-die', 'medium', true),
('Tell me about a small habit of mine that makes you smile?', 'vibe', 'ride-or-die', 'medium', true),
('If we could swap one daily routine, what would we want to try from my life?', 'vibe', 'ride-or-die', 'medium', true),
('Tell me about a challenge we''ve overcome together that made us stronger?', 'vibe', 'ride-or-die', 'medium', true),
('Tell me about your favorite thing about how we handle disagreements?', 'vibe', 'ride-or-die', 'medium', true),
('Describe something you''ve learned about yourself through our relationship?', 'vibe', 'ride-or-die', 'medium', true),
('Tell me about a way I''ve helped you heal from past wounds?', 'vibe', 'ride-or-die', 'medium', true),
('Tell me about something about our relationship that scares you?', 'vibe', 'ride-or-die', 'medium', true),
('Tell me about the most important thing you''ve learned about love from being with me?', 'vibe', 'ride-or-die', 'medium', true),
('Tell me about a way you''ve changed because of our relationship?', 'vibe', 'ride-or-die', 'medium', true),
('Tell me about something you''re grateful for about our relationship that you don''t usually say?', 'vibe', 'ride-or-die', 'medium', true),
('Describe a challenge we''ve overcome together that made us stronger?', 'vibe', 'ride-or-die', 'medium', true),
('Describe your favorite thing about how we handle disagreements?', 'vibe', 'ride-or-die', 'medium', true),
('Share something you''ve learned about yourself through our relationship?', 'vibe', 'ride-or-die', 'medium', true),
('Describe a way I''ve helped you heal from past wounds?', 'vibe', 'ride-or-die', 'medium', true),
('Describe something about our relationship that scares you?', 'vibe', 'ride-or-die', 'medium', true),
('Describe the most important thing you''ve learned about love from being with me?', 'vibe', 'ride-or-die', 'medium', true),
('Describe a way you''ve changed because of our relationship?', 'vibe', 'ride-or-die', 'medium', true),
('Describe something you''re grateful for about our relationship that you don''t usually say?', 'vibe', 'ride-or-die', 'medium', true),
('Describe the most vulnerable thing you''ve shared with me?', 'vibe', 'ride-or-die', 'medium', true),
('Describe your love language and how do you show it?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something about me that surprised you when we first met? and how has it shaped us?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a way I make you feel most loved? and how has it shaped us?', 'vibe', 'ride-or-die', 'medium', true),
('Explain something you''ve learned about yourself through our relationship?', 'vibe', 'ride-or-die', 'medium', true),
('Describe your favorite memory of us together?', 'vibe', 'ride-or-die', 'medium', true),
('Describe something you''ve always wanted to tell me but haven''t?', 'vibe', 'ride-or-die', 'medium', true),
('Describe a small habit of mine that makes you smile?', 'vibe', 'ride-or-die', 'medium', true),
('If we could swap one daily routine, what would you want to try from my life? and how has it shaped us?', 'vibe', 'ride-or-die', 'medium', true),
('Share a challenge we''ve overcome together that made us stronger?', 'vibe', 'ride-or-die', 'medium', true),
('Share your favorite thing about how we handle disagreements?', 'vibe', 'ride-or-die', 'medium', true),
('Reflect on something you''ve learned about yourself through our relationship?', 'vibe', 'ride-or-die', 'medium', true),
('Share a way I''ve helped you heal from past wounds?', 'vibe', 'ride-or-die', 'medium', true),
('Share something about our relationship that scares you?', 'vibe', 'ride-or-die', 'medium', true),
('Share the most important thing you''ve learned about love from being with me?', 'vibe', 'ride-or-die', 'medium', true),
('Share a way you''ve changed because of our relationship?', 'vibe', 'ride-or-die', 'medium', true),
('Share something you''re grateful for about our relationship that you don''t usually say?', 'vibe', 'ride-or-die', 'medium', true),
('Explain a challenge we''ve overcome together that made us stronger?', 'vibe', 'ride-or-die', 'medium', true),
('Explain your favorite thing about how we handle disagreements?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something we''ve learned about yourself through our relationship?', 'vibe', 'ride-or-die', 'medium', true),
('Explain a way I''ve helped you heal from past wounds?', 'vibe', 'ride-or-die', 'medium', true),
('Explain something about our relationship that scares you?', 'vibe', 'ride-or-die', 'medium', true),
('Explain the most important thing you''ve learned about love from being with me?', 'vibe', 'ride-or-die', 'medium', true),
('Explain a way you''ve changed because of our relationship?', 'vibe', 'ride-or-die', 'medium', true),
('Explain something you''re grateful for about our relationship that you don''t usually say?', 'vibe', 'ride-or-die', 'medium', true),
('Share the most vulnerable thing you''ve shared with me?', 'vibe', 'ride-or-die', 'medium', true),
('Share your love language and how do you show it?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something about me that surprised you when we first met? and what does it mean for us?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a way I make you feel most loved? and what does it mean for us?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something you''ve learned about yourself through our bond?', 'vibe', 'ride-or-die', 'medium', true),
('Share your favorite memory of us together?', 'vibe', 'ride-or-die', 'medium', true),
('Share something you''ve always wanted to tell me but haven''t?', 'vibe', 'ride-or-die', 'medium', true),
('Share a small habit of mine that makes you smile?', 'vibe', 'ride-or-die', 'medium', true),
('If we could swap one daily routine, what would you want to try from my life? and what does it mean for us?', 'vibe', 'ride-or-die', 'medium', true),
('Reflect on a challenge we''ve overcome together that made us stronger?', 'vibe', 'ride-or-die', 'medium', true),
('Reflect on your favorite thing about how we handle disagreements?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something you''ve learned about yourself through us?', 'vibe', 'ride-or-die', 'medium', true),
('Reflect on a way I''ve helped you heal from past wounds?', 'vibe', 'ride-or-die', 'medium', true),
('Reflect on something about our relationship that scares you?', 'vibe', 'ride-or-die', 'medium', true),
('Reflect on the most important thing you''ve learned about love from being with me?', 'vibe', 'ride-or-die', 'medium', true),
('Reflect on a way you''ve changed because of our relationship?', 'vibe', 'ride-or-die', 'medium', true),
('Reflect on something you''re grateful for about our relationship that you don''t usually say?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a challenge we''ve overcome together that made us stronger? and how has it shaped us?', 'vibe', 'ride-or-die', 'medium', true),
('What''s wer favorite thing about how we handle disagreements?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something you''ve learned about yourself through our connection?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a way I''ve helped we heal from past wounds?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something about our relationship that scares we?', 'vibe', 'ride-or-die', 'medium', true),
('What''s the most important thing we''ve learned about love from being with me?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a way we''ve changed because of our relationship?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something we''re grateful for about our relationship that you don''t usually say?', 'vibe', 'ride-or-die', 'medium', true),
('Explain the most vulnerable thing you''ve shared with me?', 'vibe', 'ride-or-die', 'medium', true),
('Explain your love language and how do you show it?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something about me that surprised you when we first met? and how has it changed us?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a way I make you feel most loved? and how has it changed us?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something you''ve learned about yourself through our love?', 'vibe', 'ride-or-die', 'medium', true),
('Explain your favorite memory of us together?', 'vibe', 'ride-or-die', 'medium', true),
('Explain something you''ve always wanted to tell me but haven''t?', 'vibe', 'ride-or-die', 'medium', true),
('Explain a small habit of mine that makes you smile?', 'vibe', 'ride-or-die', 'medium', true),
('If we could swap one daily routine, what would you want to try from my life? and how has it changed us?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a challenge we''ve overcome together that made us stronger? and what does it mean for us?', 'vibe', 'ride-or-die', 'medium', true),
('What''s your favorite thing about how we handle disagreements? and how has it shaped us?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something you''ve learned about yourself through our partnership?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a way I''ve helped you heal from past wounds? and how has it shaped us?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something about our bond that scares you?', 'vibe', 'ride-or-die', 'medium', true),
('What''s the most important thing you''ve learned about love from being with me? and how has it shaped us?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a way you''ve changed because of our bond?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something you''re grateful for about our bond that you don''t usually say?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a challenge we''ve overcome together that made us stronger? and how has it changed us?', 'vibe', 'ride-or-die', 'medium', true),
('What''s your favorite thing about how we handle disagreements? and what does it mean for us?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something you''ve learned about yourself through our journey?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a way I''ve helped you heal from past wounds? and what does it mean for us?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something about us that scares you?', 'vibe', 'ride-or-die', 'medium', true),
('What''s the most important thing you''ve learned about love from being with me? and what does it mean for us?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a way you''ve changed because of us?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something you''re grateful for about us that you don''t usually say?', 'vibe', 'ride-or-die', 'medium', true),
('Reflect on the most vulnerable thing you''ve shared with me?', 'vibe', 'ride-or-die', 'medium', true),
('Reflect on your love language and how do you show it?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a moment when you felt most vulnerable with me?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something about our spiritual connection that you appreciate?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something you''ve learned about yourself through our story?', 'vibe', 'ride-or-die', 'medium', true),
('Reflect on your favorite memory of us together?', 'vibe', 'ride-or-die', 'medium', true),
('Reflect on something you''ve always wanted to tell me but haven''t?', 'vibe', 'ride-or-die', 'medium', true),
('Reflect on a small habit of mine that makes you smile?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a way we''ve enhanced our understanding that you appreciate?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something about our emotional support that you cherish?', 'vibe', 'ride-or-die', 'medium', true),
('What''s your favorite thing about how we handle disagreements? and how has it changed us?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something you''ve learned about yourself through our life together?', 'vibe', 'ride-or-die', 'medium', true),
('Tell me about our biggest shared dream?', 'lockin', 'ride-or-die', 'hard', true),
('Tell me about the most vulnerable thing you''ve ever shared with me?', 'lockin', 'ride-or-die', 'hard', true),
('Tell me about something you want to change about our relationship?', 'lockin', 'ride-or-die', 'hard', true),
('Tell me about your deepest fear about our future together?', 'lockin', 'ride-or-die', 'hard', true),
('Tell me about the most important lesson you''ve learned from our relationship?', 'lockin', 'ride-or-die', 'hard', true),
('Tell me about your vision for our life together in 10 years?', 'lockin', 'ride-or-die', 'hard', true),
('Tell me about something you''d never want to lose about our connection?', 'lockin', 'ride-or-die', 'hard', true),
('Tell me about the hardest thing you''ve had to forgive me for?', 'lockin', 'ride-or-die', 'hard', true),
('Tell me about a dream we''ve never shared that could change our future together?', 'lockin', 'ride-or-die', 'hard', true),
('Tell me about the most difficult conversation we''ve ever had and what did it teach us?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a way I''ve helped you heal from past wounds? and what does it mean for our future?', 'lockin', 'ride-or-die', 'hard', true),
('Tell me about your deepest insecurity and how can I help you overcome it?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something about our connection that scares you?', 'lockin', 'ride-or-die', 'hard', true),
('What''s the most important thing you''ve learned about love from being with me? and what does it mean for our future?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a way you''ve changed because of our connection?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something you''re grateful for about our connection that you don''t usually say?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a challenge we''ve overcome together that made us stronger? and what does it mean for our future?', 'lockin', 'ride-or-die', 'hard', true),
('What''s your favorite thing about how we handle disagreements? and what does it mean for our future?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something you''ve learned about yourself through our future?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a way I''ve helped you heal from past wounds? and how will it impact us?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something about our love that scares you?', 'lockin', 'ride-or-die', 'hard', true),
('What''s the most important thing you''ve learned about love from being with me? and how will it impact us?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a way you''ve changed because of our love?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something you''re grateful for about our love that you don''t usually say?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a challenge we''ve overcome together that made us stronger? and how will it impact us?', 'lockin', 'ride-or-die', 'hard', true),
('Describe our biggest shared dream?', 'lockin', 'ride-or-die', 'hard', true),
('Describe the most vulnerable thing you''ve ever shared with me?', 'lockin', 'ride-or-die', 'hard', true),
('Describe something you want to change about our relationship?', 'lockin', 'ride-or-die', 'hard', true),
('Describe your deepest fear about our future together?', 'lockin', 'ride-or-die', 'hard', true),
('Describe the most important lesson you''ve learned from our relationship?', 'lockin', 'ride-or-die', 'hard', true),
('Describe your vision for our life together in 10 years?', 'lockin', 'ride-or-die', 'hard', true),
('Describe something you''d never want to lose about our connection?', 'lockin', 'ride-or-die', 'hard', true),
('Describe the hardest thing you''ve had to forgive me for?', 'lockin', 'ride-or-die', 'hard', true),
('Describe a dream we''ve never shared that could change our future together?', 'lockin', 'ride-or-die', 'hard', true),
('Describe the most difficult conversation we''ve ever had and what did it teach us?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a way I''ve helped you heal from past wounds? and what does it reveal about us?', 'lockin', 'ride-or-die', 'hard', true),
('Describe your deepest insecurity and how can I help you overcome it?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something about our partnership that scares you?', 'lockin', 'ride-or-die', 'hard', true),
('What''s the most important thing you''ve learned about love from being with me? and what does it reveal about us?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a way you''ve changed because of our partnership?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something you''re grateful for about our partnership that you don''t usually say?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a challenge we''ve overcome together that made us stronger? and what does it reveal about us?', 'lockin', 'ride-or-die', 'hard', true),
('What''s your favorite thing about how we handle disagreements? and how will it impact us?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something you''ve learned about yourself through our past?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something about our divine union that you believe in?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something about our journey that scares you?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something about our cosmic bond that you feel?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a way you''ve changed because of our journey?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something you''re grateful for about our journey that you don''t usually say?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a moment when you felt our love was transcendent?', 'lockin', 'ride-or-die', 'hard', true),
('Share our biggest shared dream?', 'lockin', 'ride-or-die', 'hard', true),
('Share the most vulnerable thing you''ve ever shared with me?', 'lockin', 'ride-or-die', 'hard', true),
('Share something you want to change about our relationship?', 'lockin', 'ride-or-die', 'hard', true),
('Share your deepest fear about our future together?', 'lockin', 'ride-or-die', 'hard', true),
('Share the most important lesson you''ve learned from our relationship?', 'lockin', 'ride-or-die', 'hard', true),
('Share your vision for our life together in 10 years?', 'lockin', 'ride-or-die', 'hard', true),
('Share something you''d never want to lose about our connection?', 'lockin', 'ride-or-die', 'hard', true),
('Share the hardest thing you''ve had to forgive me for?', 'lockin', 'ride-or-die', 'hard', true),
('Share a dream we''ve never shared that could change our future together?', 'lockin', 'ride-or-die', 'hard', true),
('Share the most difficult conversation we''ve ever had and what did it teach us?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a way we''ve reached a new level of love that you appreciate?', 'lockin', 'ride-or-die', 'hard', true),
('Share your deepest insecurity and how can I help you overcome it?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something about our story that scares you?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something about our cosmic connection that you feel?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a way you''ve changed because of our story?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something you''re grateful for about our story that you don''t usually say?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a moment when you felt our love was immortal?', 'lockin', 'ride-or-die', 'hard', true),
('What''s your favorite thing about how we handle disagreements? and what does it reveal about us?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something you''ve learned about yourself through our present?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something about our divine union that you believe in?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something about our life together that scares you?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something about our cosmic bond that you feel?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a way you''ve changed because of our life together?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something you''re grateful for about our life together that you don''t usually say?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a moment when you felt our love was transcendent?', 'lockin', 'ride-or-die', 'hard', true),
('Explain our biggest shared dream?', 'lockin', 'ride-or-die', 'hard', true),
('Explain the most vulnerable thing you''ve ever shared with me?', 'lockin', 'ride-or-die', 'hard', true),
('Explain something you want to change about our relationship?', 'lockin', 'ride-or-die', 'hard', true),
('Explain your deepest fear about our future together?', 'lockin', 'ride-or-die', 'hard', true),
('Explain the most important lesson you''ve learned from our relationship?', 'lockin', 'ride-or-die', 'hard', true),
('Explain your vision for our life together in 10 years?', 'lockin', 'ride-or-die', 'hard', true),
('Explain something you''d never want to lose about our connection?', 'lockin', 'ride-or-die', 'hard', true),
('Explain the hardest thing you''ve had to forgive me for?', 'lockin', 'ride-or-die', 'hard', true),
('Explain a dream we''ve never shared that could change our future together?', 'lockin', 'ride-or-die', 'hard', true),
('Explain the most difficult conversation we''ve ever had and what did it teach us?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a way we''ve reached a new level of love that you appreciate?', 'lockin', 'ride-or-die', 'hard', true),
('Explain your deepest insecurity and how can I help you overcome it?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something about our future that scares you?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something about our cosmic connection that you feel?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a way you''ve changed because of our future?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something you''re grateful for about our future that you don''t usually say?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a moment when you felt our love was immortal?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something about our sacred bond that you honor?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something you''ve learned about yourself through our dreams?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something about our divine union that you believe in?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something about our past that scares you?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something about our cosmic bond that you feel?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a way you''ve changed because of our past?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something you''re grateful for about our past that you don''t usually say?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a moment when you felt our love was transcendent?', 'lockin', 'ride-or-die', 'hard', true),
('Reflect on our biggest shared dream?', 'lockin', 'ride-or-die', 'hard', true),
('Reflect on the most vulnerable thing you''ve ever shared with me?', 'lockin', 'ride-or-die', 'hard', true),
('Reflect on something you want to change about our relationship?', 'lockin', 'ride-or-die', 'hard', true),
('Reflect on your deepest fear about our future together?', 'lockin', 'ride-or-die', 'hard', true),
('Reflect on the most important lesson you''ve learned from our relationship?', 'lockin', 'ride-or-die', 'hard', true),
('Reflect on your vision for our life together in 10 years?', 'lockin', 'ride-or-die', 'hard', true),
('Reflect on something you''d never want to lose about our connection?', 'lockin', 'ride-or-die', 'hard', true),
('Reflect on the hardest thing you''ve had to forgive me for?', 'lockin', 'ride-or-die', 'hard', true),
('Reflect on a dream we''ve never shared that could change our future together?', 'lockin', 'ride-or-die', 'hard', true),
('Reflect on the most difficult conversation we''ve ever had and what did it teach us?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a way we''ve reached a new level of love that you appreciate?', 'lockin', 'ride-or-die', 'hard', true);

-- Verify counts
SELECT 
  category,
  tier,
  is_premium_only,
  COUNT(*) as count
FROM prompts 
GROUP BY category, tier, is_premium_only 
ORDER BY category, tier, is_premium_only;
