-- Insert Free Prompts into the prompts table
-- This script inserts all 75 free prompts (25 per tier) for both Squad and Ride-or-Die categories

-- Clear existing free prompts
DELETE FROM prompts WHERE is_premium_only = false;

-- Insert Squad Vibes Free Prompts (75 total - 25 per tier)
-- Spark Stage Squad (25 prompts)
INSERT INTO prompts (prompt_text, tier, category, difficulty, is_premium_only) VALUES
('What''s your wildest group chat secret that would embarrass you if it got out?', 'spark', 'squad', 'easy', false),
('What''s the most embarrassing thing that happened to you this week that we can all laugh about?', 'spark', 'squad', 'easy', false),
('What''s the cringiest thing you used to do in middle school?', 'spark', 'squad', 'easy', false),
('What''s the most ridiculous lie you''ve ever told that actually worked?', 'spark', 'squad', 'easy', false),
('What''s your most embarrassing autocorrect fail that you wish you could take back?', 'spark', 'squad', 'easy', false),
('What''s the weirdest thing you do when you think no one is watching?', 'spark', 'squad', 'easy', false),
('What''s the most ridiculous thing you''ve cried about recently?', 'spark', 'squad', 'easy', false),
('What''s your most embarrassing celebrity crush that you''re too old for?', 'spark', 'squad', 'easy', false),
('What''s the most overrated thing everyone loves but you secretly hate?', 'spark', 'squad', 'easy', false),
('What''s your most useless talent that you''re weirdly proud of?', 'spark', 'squad', 'easy', false),
('What''s the most ridiculous thing you''ve convinced someone of just to see if they''d believe it?', 'spark', 'squad', 'easy', false),
('What''s your most embarrassing social media post from years ago that still haunts you?', 'spark', 'squad', 'easy', false),
('What''s the weirdest food combination you actually enjoy that would gross everyone out?', 'spark', 'squad', 'easy', false),
('What''s your most ridiculous fear that you know is totally irrational?', 'spark', 'squad', 'easy', false),
('What''s the most embarrassing thing you''ve done for attention or likes?', 'spark', 'squad', 'easy', false),
('If you had to pick one friend from the group to survive a zombie apocalypse with, who and why?', 'spark', 'squad', 'easy', false),
('What''s the most embarrassing thing you''ve ever done to impress someone in our group?', 'spark', 'squad', 'easy', false),
('What''s the weirdest dream you''ve had about one of us?', 'spark', 'squad', 'easy', false),
('If we were all characters in a movie, what would be our group''s theme song?', 'spark', 'squad', 'easy', false),
('What''s the most ridiculous thing you''ve ever bought online while drunk or sleep-deprived?', 'spark', 'squad', 'easy', false),
('What''s your most embarrassing childhood nickname that you hope never comes back?', 'spark', 'squad', 'easy', false),
('What''s the weirdest thing you''ve googled recently that you''d be embarrassed if anyone saw?', 'spark', 'squad', 'easy', false),
('What''s the most ridiculous thing you''ve done to avoid an awkward social situation?', 'spark', 'squad', 'easy', false),
('What''s your most embarrassing autocorrect fail that you wish you could take back?', 'spark', 'squad', 'easy', false),
('What''s the weirdest thing you do when you think no one is watching?', 'spark', 'squad', 'easy', false),

-- Vibe Check Squad (25 prompts)
('What''s something you''re struggling with right now that you haven''t told anyone?', 'vibe', 'squad', 'medium', false),
('What''s a fear you have that your friends don''t know about but you think they''d understand?', 'vibe', 'squad', 'medium', false),
('What''s something you''re insecure about that you think we could help each other with?', 'vibe', 'squad', 'medium', false),
('What''s a dream or goal you have that you''re scared to pursue?', 'vibe', 'squad', 'medium', false),
('What''s something you''ve been hiding from us that you think we''d actually support?', 'vibe', 'squad', 'medium', false),
('What''s a way you''ve changed recently that you want us to notice and celebrate?', 'vibe', 'squad', 'medium', false),
('What''s something you''re really proud of but feel weird bragging about?', 'vibe', 'squad', 'medium', false),
('What''s a belief or value that''s really important to you that you think we''d respect?', 'vibe', 'squad', 'medium', false),
('What''s the most embarrassing story from our group hangouts that still makes you laugh?', 'vibe', 'squad', 'medium', false),
('What''s something you''ve learned about friendship from our group?', 'vibe', 'squad', 'medium', false),
('What''s a way someone in our group has supported you when you needed it most?', 'vibe', 'squad', 'medium', false),
('What''s something you want to change about how we support each other?', 'vibe', 'squad', 'medium', false),
('What''s your biggest fear about losing our friendship?', 'vibe', 'squad', 'medium', false),
('What''s the most meaningful way someone in our group has supported you?', 'vibe', 'squad', 'medium', false),
('What''s something you''d never want to lose about our bond?', 'vibe', 'squad', 'medium', false),
('What''s the hardest thing you''ve had to forgive one of us for?', 'vibe', 'squad', 'medium', false),
('What''s your vision for our friendship in 10 years?', 'vibe', 'squad', 'medium', false),
('What''s something you''ve never told anyone that you think we''d understand?', 'vibe', 'squad', 'medium', false),
('What''s the most important thing you''ve learned about friendship from our group?', 'vibe', 'squad', 'medium', false),
('What''s a way you''ve helped one of us through a tough time?', 'vibe', 'squad', 'medium', false),
('What''s something you''re grateful for about our friendship that you don''t usually say?', 'vibe', 'squad', 'medium', false),
('What''s a challenge we''ve overcome together that made us stronger?', 'vibe', 'squad', 'medium', false),
('What''s your favorite thing about how we handle disagreements?', 'vibe', 'squad', 'medium', false),
('What''s something you''ve learned about yourself through our friendship?', 'vibe', 'squad', 'medium', false),
('What''s a way you''ve changed because of our friendship?', 'vibe', 'squad', 'medium', false),

-- Lock-In Level Squad (25 prompts)
('What''s the most important thing you''ve learned about friendship from our group?', 'lockin', 'squad', 'hard', false),
('What''s something you''ve never told anyone that you think we''d understand?', 'lockin', 'squad', 'hard', false),
('What''s your biggest fear about losing our friendship?', 'lockin', 'squad', 'hard', false),
('What''s the most meaningful way someone in our group has supported you?', 'lockin', 'squad', 'hard', false),
('What''s something you want to change about how we support each other?', 'lockin', 'squad', 'hard', false),
('What''s your vision for our friendship in 10 years?', 'lockin', 'squad', 'hard', false),
('What''s something you''d never want to lose about our bond?', 'lockin', 'squad', 'hard', false),
('What''s the hardest thing you''ve had to forgive one of us for?', 'lockin', 'squad', 'hard', false),
('If we could relive one group memory but change one thing, what would it be?', 'lockin', 'squad', 'hard', false),
('What''s the most vulnerable thing you''ve never told any of us?', 'lockin', 'squad', 'hard', false),
('What''s a way you''ve helped one of us through our darkest time?', 'lockin', 'squad', 'hard', false),
('What''s something you''ve learned about yourself through our friendship?', 'lockin', 'squad', 'hard', false),
('What''s a way you''ve changed because of our friendship?', 'lockin', 'squad', 'hard', false),
('What''s something you''re grateful for about our friendship that you don''t usually say?', 'lockin', 'squad', 'hard', false),
('What''s a challenge we''ve overcome together that made us stronger?', 'lockin', 'squad', 'hard', false),
('What''s your favorite thing about how we handle disagreements?', 'lockin', 'squad', 'hard', false),
('What''s something you''ve learned about yourself through our friendship?', 'lockin', 'squad', 'hard', false),
('What''s a way you''ve helped one of us through a tough time?', 'lockin', 'squad', 'hard', false),
('What''s something you''re grateful for about our friendship that you don''t usually say?', 'lockin', 'squad', 'hard', false),
('What''s a challenge we''ve overcome together that made us stronger?', 'lockin', 'squad', 'hard', false),
('What''s your favorite thing about how we handle disagreements?', 'lockin', 'squad', 'hard', false),
('What''s something you''ve learned about yourself through our friendship?', 'lockin', 'squad', 'hard', false),
('What''s a way you''ve helped one of us through a tough time?', 'lockin', 'squad', 'hard', false),
('What''s something you''re grateful for about our friendship that you don''t usually say?', 'lockin', 'squad', 'hard', false),
('What''s a challenge we''ve overcome together that made us stronger?', 'lockin', 'squad', 'hard', false);

-- Insert Ride-or-Die Free Prompts (75 total - 25 per tier)
-- Spark Stage Ride-or-Die (25 prompts)
INSERT INTO prompts (prompt_text, tier, category, difficulty, is_premium_only) VALUES
('What''s something about yourself that you think I don''t know yet?', 'spark', 'ride-or-die', 'easy', false),
('What''s a childhood memory that shaped who you are today?', 'spark', 'ride-or-die', 'easy', false),
('What''s something you''re secretly really good at that might surprise me?', 'spark', 'ride-or-die', 'easy', false),
('What''s a fear or insecurity you have that you haven''t shared with me?', 'spark', 'ride-or-die', 'easy', false),
('What''s something you''ve always wanted to try but never had the courage to do?', 'spark', 'ride-or-die', 'easy', false),
('What''s a belief or value that''s really important to you that I might not know about?', 'spark', 'ride-or-die', 'easy', false),
('What''s something you''re proud of that you''ve never told me about?', 'spark', 'ride-or-die', 'easy', false),
('What''s a way you''ve changed or grown recently that you want me to notice?', 'spark', 'ride-or-die', 'easy', false),
('What''s something you''re curious about me that you''ve never asked?', 'spark', 'ride-or-die', 'easy', false),
('What''s a dream or goal you have that you haven''t shared with me yet?', 'spark', 'ride-or-die', 'easy', false),
('What''s something you wish you could tell your past self about relationships?', 'spark', 'ride-or-die', 'easy', false),
('What''s a way you show love or care that you think I might not notice?', 'spark', 'ride-or-die', 'easy', false),
('What''s something you''re working on improving about yourself right now?', 'spark', 'ride-or-die', 'easy', false),
('What''s a quality you admire in others that you wish you had more of?', 'spark', 'ride-or-die', 'easy', false),
('What''s something you''re grateful for that you don''t usually talk about?', 'spark', 'ride-or-die', 'easy', false),
('What''s a quirky habit of mine you secretly love?', 'spark', 'ride-or-die', 'easy', false),
('What''s something about me that surprised you when we first met?', 'spark', 'ride-or-die', 'easy', false),
('What''s a small thing I do that makes you smile?', 'spark', 'ride-or-die', 'easy', false),
('What''s something you''ve learned about yourself since we''ve been together?', 'spark', 'ride-or-die', 'easy', false),
('What''s a memory of us that you think about often?', 'spark', 'ride-or-die', 'easy', false),
('What''s something you''re curious about my past that you''ve never asked?', 'spark', 'ride-or-die', 'easy', false),
('What''s a way I make you feel most loved?', 'spark', 'ride-or-die', 'easy', false),
('What''s something you''ve always wanted to tell me but haven''t found the right moment?', 'spark', 'ride-or-die', 'easy', false),
('What''s a dream you have for us that you haven''t shared yet?', 'spark', 'ride-or-die', 'easy', false),
('What''s something about our relationship that makes you feel most secure?', 'spark', 'ride-or-die', 'easy', false),

-- Vibe Check Ride-or-Die (25 prompts)
('What''s a small habit of mine that makes you smile?', 'vibe', 'ride-or-die', 'medium', false),
('What''s your favorite memory of us together?', 'vibe', 'ride-or-die', 'medium', false),
('What''s something you''ve always wanted to tell me but haven''t?', 'vibe', 'ride-or-die', 'medium', false),
('What''s your love language and how do you show it?', 'vibe', 'ride-or-die', 'medium', false),
('What''s the most vulnerable thing you''ve shared with me?', 'vibe', 'ride-or-die', 'medium', false),
('What''s something about me that surprised you when we first met?', 'vibe', 'ride-or-die', 'medium', false),
('What''s a way I make you feel most loved?', 'vibe', 'ride-or-die', 'medium', false),
('What''s something you''ve learned about yourself through our relationship?', 'vibe', 'ride-or-die', 'medium', false),
('If we could swap one daily routine, what would you want to try from my life?', 'vibe', 'ride-or-die', 'medium', false),
('What''s a challenge we''ve overcome together that made us stronger?', 'vibe', 'ride-or-die', 'medium', false),
('What''s your favorite thing about how we handle disagreements?', 'vibe', 'ride-or-die', 'medium', false),
('What''s something you''ve learned about yourself through our relationship?', 'vibe', 'ride-or-die', 'medium', false),
('What''s a way I''ve helped you heal from past wounds?', 'vibe', 'ride-or-die', 'medium', false),
('What''s something about our relationship that scares you?', 'vibe', 'ride-or-die', 'medium', false),
('What''s the most important thing you''ve learned about love from being with me?', 'vibe', 'ride-or-die', 'medium', false),
('What''s a way you''ve changed because of our relationship?', 'vibe', 'ride-or-die', 'medium', false),
('What''s something you''re grateful for about our relationship that you don''t usually say?', 'vibe', 'ride-or-die', 'medium', false),
('What''s a challenge we''ve overcome together that made us stronger?', 'vibe', 'ride-or-die', 'medium', false),
('What''s your favorite thing about how we handle disagreements?', 'vibe', 'ride-or-die', 'medium', false),
('What''s something you''ve learned about yourself through our relationship?', 'vibe', 'ride-or-die', 'medium', false),
('What''s a way I''ve helped you heal from past wounds?', 'vibe', 'ride-or-die', 'medium', false),
('What''s something about our relationship that scares you?', 'vibe', 'ride-or-die', 'medium', false),
('What''s the most important thing you''ve learned about love from being with me?', 'vibe', 'ride-or-die', 'medium', false),
('What''s a way you''ve changed because of our relationship?', 'vibe', 'ride-or-die', 'medium', false),
('What''s something you''re grateful for about our relationship that you don''t usually say?', 'vibe', 'ride-or-die', 'medium', false),

-- Lock-In Level Ride-or-Die (25 prompts)
('What''s our biggest shared dream?', 'lockin', 'ride-or-die', 'hard', false),
('What''s the most vulnerable thing you''ve ever shared with me?', 'lockin', 'ride-or-die', 'hard', false),
('What''s something you want to change about our relationship?', 'lockin', 'ride-or-die', 'hard', false),
('What''s your deepest fear about our future together?', 'lockin', 'ride-or-die', 'hard', false),
('What''s the most important lesson you''ve learned from our relationship?', 'lockin', 'ride-or-die', 'hard', false),
('What''s your vision for our life together in 10 years?', 'lockin', 'ride-or-die', 'hard', false),
('What''s something you''d never want to lose about our connection?', 'lockin', 'ride-or-die', 'hard', false),
('What''s the hardest thing you''ve had to forgive me for?', 'lockin', 'ride-or-die', 'hard', false),
('What''s a dream we''ve never shared that could change our future together?', 'lockin', 'ride-or-die', 'hard', false),
('What''s the most difficult conversation we''ve ever had and what did it teach us?', 'lockin', 'ride-or-die', 'hard', false),
('What''s a way I''ve helped you heal from past wounds?', 'lockin', 'ride-or-die', 'hard', false),
('What''s your deepest insecurity and how can I help you overcome it?', 'lockin', 'ride-or-die', 'hard', false),
('What''s something about our relationship that scares you?', 'lockin', 'ride-or-die', 'hard', false),
('What''s the most important thing you''ve learned about love from being with me?', 'lockin', 'ride-or-die', 'hard', false),
('What''s a way you''ve changed because of our relationship?', 'lockin', 'ride-or-die', 'hard', false),
('What''s something you''re grateful for about our relationship that you don''t usually say?', 'lockin', 'ride-or-die', 'hard', false),
('What''s a challenge we''ve overcome together that made us stronger?', 'lockin', 'ride-or-die', 'hard', false),
('What''s your favorite thing about how we handle disagreements?', 'lockin', 'ride-or-die', 'hard', false),
('What''s something you''ve learned about yourself through our relationship?', 'lockin', 'ride-or-die', 'hard', false),
('What''s a way I''ve helped you heal from past wounds?', 'lockin', 'ride-or-die', 'hard', false),
('What''s something about our relationship that scares you?', 'lockin', 'ride-or-die', 'hard', false),
('What''s the most important thing you''ve learned about love from being with me?', 'lockin', 'ride-or-die', 'hard', false),
('What''s a way you''ve changed because of our relationship?', 'lockin', 'ride-or-die', 'hard', false),
('What''s something you''re grateful for about our relationship that you don''t usually say?', 'lockin', 'ride-or-die', 'hard', false),
('What''s a challenge we''ve overcome together that made us stronger?', 'lockin', 'ride-or-die', 'hard', false);
