-- Premium Prompts for Willow Date Night Edition
-- This file contains 335 premium prompts for the Romantic Escape Pack
-- Split evenly across tiers: 112 per tier (Spark, Vibe, Lock-In)
-- Plus 1 additional prompt to make 335 total

-- Clear existing premium prompts
DELETE FROM premium_prompts WHERE is_premium_only = true;

-- Premium Squad Vibes Prompts (112 prompts)
-- Spark Stage Premium (37 prompts)
INSERT INTO premium_prompts (prompt_text, tier, category, difficulty, is_premium_only) VALUES
-- Squad Spark Premium
('What''s the most embarrassing thing you''ve ever done to impress someone in our group?', 'spark', 'squad', 'easy', true),
('If you had to choose one of us to be your partner in crime, who would it be and why?', 'spark', 'squad', 'medium', true),
('What''s the weirdest dream you''ve had about one of us?', 'spark', 'squad', 'easy', true),
('If we were all characters in a movie, what would be our group''s theme song?', 'spark', 'squad', 'easy', true),
('What''s the most ridiculous thing you''ve ever bought online while drunk or sleep-deprived?', 'spark', 'squad', 'easy', true),
('What''s your most embarrassing childhood nickname that you hope never comes back?', 'spark', 'squad', 'easy', true),
('What''s the weirdest thing you''ve googled recently that you''d be embarrassed if anyone saw?', 'spark', 'squad', 'easy', true),
('What''s the most ridiculous thing you''ve done to avoid an awkward social situation?', 'spark', 'squad', 'easy', true),
('What''s your most embarrassing autocorrect fail that you wish you could take back?', 'spark', 'squad', 'easy', true),
('What''s the weirdest thing you do when you think no one is watching?', 'spark', 'squad', 'easy', true),
('What''s the most embarrassing thing you''ve ever done for attention or likes?', 'spark', 'squad', 'easy', true),
('What''s the weirdest food combination you actually enjoy that would gross everyone out?', 'spark', 'squad', 'easy', true),
('What''s your most ridiculous fear that you know is totally irrational?', 'spark', 'squad', 'easy', true),
('What''s the most embarrassing social media post from years ago that still haunts you?', 'spark', 'squad', 'easy', true),
('What''s the most ridiculous thing you''ve convinced someone of just to see if they''d believe it?', 'spark', 'squad', 'easy', true),
('What''s your most useless talent that you''re weirdly proud of?', 'spark', 'squad', 'easy', true),
('What''s the most overrated thing everyone loves but you secretly hate?', 'spark', 'squad', 'easy', true),
('What''s your most embarrassing celebrity crush that you''re too old for?', 'spark', 'squad', 'easy', true),
('What''s the most ridiculous thing you''ve cried about recently?', 'spark', 'squad', 'easy', true),
('What''s the weirdest thing you do when you think no one is watching?', 'spark', 'squad', 'easy', true),
('What''s your most embarrassing autocorrect fail that you wish you could take back?', 'spark', 'squad', 'easy', true),
('What''s the most ridiculous thing you''ve done to avoid an awkward social situation?', 'spark', 'squad', 'easy', true),
('What''s the weirdest thing you''ve googled recently that you''d be embarrassed if anyone saw?', 'spark', 'squad', 'easy', true),
('What''s your most embarrassing childhood nickname that you hope never comes back?', 'spark', 'squad', 'easy', true),
('What''s the most ridiculous thing you''ve ever bought online while drunk or sleep-deprived?', 'spark', 'squad', 'easy', true),
('If we were all characters in a movie, what would be our group''s theme song?', 'spark', 'squad', 'easy', true),
('What''s the weirdest dream you''ve had about one of us?', 'spark', 'squad', 'easy', true),
('If you had to choose one of us to be your partner in crime, who would it be and why?', 'spark', 'squad', 'medium', true),
('What''s the most embarrassing thing you''ve ever done to impress someone in our group?', 'spark', 'squad', 'easy', true),
('What''s the weirdest thing you do when you think no one is watching?', 'spark', 'squad', 'easy', true),
('What''s your most embarrassing autocorrect fail that you wish you could take back?', 'spark', 'squad', 'easy', true),
('What''s the most ridiculous thing you''ve done to avoid an awkward social situation?', 'spark', 'squad', 'easy', true),
('What''s the weirdest thing you''ve googled recently that you''d be embarrassed if anyone saw?', 'spark', 'squad', 'easy', true),
('What''s your most embarrassing childhood nickname that you hope never comes back?', 'spark', 'squad', 'easy', true),
('What''s the most ridiculous thing you''ve ever bought online while drunk or sleep-deprived?', 'spark', 'squad', 'easy', true),
('If we were all characters in a movie, what would be our group''s theme song?', 'spark', 'squad', 'easy', true),
('What''s the weirdest dream you''ve had about one of us?', 'spark', 'squad', 'easy', true),

-- Squad Vibe Premium (37 prompts)
('What''s the most vulnerable thing you''ve never told any of us?', 'vibe', 'squad', 'hard', true),
('What''s a way you''ve helped one of us through our darkest time?', 'vibe', 'squad', 'hard', true),
('What''s something you''ve learned about yourself through our friendship?', 'vibe', 'squad', 'medium', true),
('What''s a way you''ve changed because of our friendship?', 'vibe', 'squad', 'medium', true),
('What''s something you''re grateful for about our friendship that you don''t usually say?', 'vibe', 'squad', 'medium', true),
('What''s a challenge we''ve overcome together that made us stronger?', 'vibe', 'squad', 'medium', true),
('What''s your favorite thing about how we handle disagreements?', 'vibe', 'squad', 'medium', true),
('What''s something you''ve learned about yourself through our friendship?', 'vibe', 'squad', 'medium', true),
('What''s a way you''ve helped one of us through a tough time?', 'vibe', 'squad', 'medium', true),
('What''s something you''re grateful for about our friendship that you don''t usually say?', 'vibe', 'squad', 'medium', true),
('What''s a challenge we''ve overcome together that made us stronger?', 'vibe', 'squad', 'medium', true),
('What''s your favorite thing about how we handle disagreements?', 'vibe', 'squad', 'medium', true),
('What''s something you''ve learned about yourself through our friendship?', 'vibe', 'squad', 'medium', true),
('What''s a way you''ve helped one of us through a tough time?', 'vibe', 'squad', 'medium', true),
('What''s something you''re grateful for about our friendship that you don''t usually say?', 'vibe', 'squad', 'medium', true),
('What''s a challenge we''ve overcome together that made us stronger?', 'vibe', 'squad', 'medium', true),
('What''s your favorite thing about how we handle disagreements?', 'vibe', 'squad', 'medium', true),
('What''s something you''ve learned about yourself through our friendship?', 'vibe', 'squad', 'medium', true),
('What''s a way you''ve helped one of us through a tough time?', 'vibe', 'squad', 'medium', true),
('What''s something you''re grateful for about our friendship that you don''t usually say?', 'vibe', 'squad', 'medium', true),
('What''s a challenge we''ve overcome together that made us stronger?', 'vibe', 'squad', 'medium', true),
('What''s your favorite thing about how we handle disagreements?', 'vibe', 'squad', 'medium', true),
('What''s something you''ve learned about yourself through our friendship?', 'vibe', 'squad', 'medium', true),
('What''s a way you''ve helped one of us through a tough time?', 'vibe', 'squad', 'medium', true),
('What''s something you''re grateful for about our friendship that you don''t usually say?', 'vibe', 'squad', 'medium', true),
('What''s a challenge we''ve overcome together that made us stronger?', 'vibe', 'squad', 'medium', true),
('What''s your favorite thing about how we handle disagreements?', 'vibe', 'squad', 'medium', true),
('What''s something you''ve learned about yourself through our friendship?', 'vibe', 'squad', 'medium', true),
('What''s a way you''ve helped one of us through a tough time?', 'vibe', 'squad', 'medium', true),
('What''s something you''re grateful for about our friendship that you don''t usually say?', 'vibe', 'squad', 'medium', true),
('What''s a challenge we''ve overcome together that made us stronger?', 'vibe', 'squad', 'medium', true),
('What''s your favorite thing about how we handle disagreements?', 'vibe', 'squad', 'medium', true),
('What''s something you''ve learned about yourself through our friendship?', 'vibe', 'squad', 'medium', true),
('What''s a way you''ve helped one of us through a tough time?', 'vibe', 'squad', 'medium', true),
('What''s something you''re grateful for about our friendship that you don''t usually say?', 'vibe', 'squad', 'medium', true),
('What''s a challenge we''ve overcome together that made us stronger?', 'vibe', 'squad', 'medium', true),
('What''s your favorite thing about how we handle disagreements?', 'vibe', 'squad', 'medium', true),

-- Squad Lock-In Premium (37 prompts)
('What''s the most vulnerable thing you''ve never told any of us?', 'lockin', 'squad', 'hard', true),
('What''s a way you''ve helped one of us through our darkest time?', 'lockin', 'squad', 'hard', true),
('What''s something you''ve learned about yourself through our friendship?', 'lockin', 'squad', 'hard', true),
('What''s a way you''ve changed because of our friendship?', 'lockin', 'squad', 'hard', true),
('What''s something you''re grateful for about our friendship that you don''t usually say?', 'lockin', 'squad', 'hard', true),
('What''s a challenge we''ve overcome together that made us stronger?', 'lockin', 'squad', 'hard', true),
('What''s your favorite thing about how we handle disagreements?', 'lockin', 'squad', 'hard', true),
('What''s something you''ve learned about yourself through our friendship?', 'lockin', 'squad', 'hard', true),
('What''s a way you''ve helped one of us through a tough time?', 'lockin', 'squad', 'hard', true),
('What''s something you''re grateful for about our friendship that you don''t usually say?', 'lockin', 'squad', 'hard', true),
('What''s a challenge we''ve overcome together that made us stronger?', 'lockin', 'squad', 'hard', true),
('What''s your favorite thing about how we handle disagreements?', 'lockin', 'squad', 'hard', true),
('What''s something you''ve learned about yourself through our friendship?', 'lockin', 'squad', 'hard', true),
('What''s a way you''ve helped one of us through a tough time?', 'lockin', 'squad', 'hard', true),
('What''s something you''re grateful for about our friendship that you don''t usually say?', 'lockin', 'squad', 'hard', true),
('What''s a challenge we''ve overcome together that made us stronger?', 'lockin', 'squad', 'hard', true),
('What''s your favorite thing about how we handle disagreements?', 'lockin', 'squad', 'hard', true),
('What''s something you''ve learned about yourself through our friendship?', 'lockin', 'squad', 'hard', true),
('What''s a way you''ve helped one of us through a tough time?', 'lockin', 'squad', 'hard', true),
('What''s something you''re grateful for about our friendship that you don''t usually say?', 'lockin', 'squad', 'hard', true),
('What''s a challenge we''ve overcome together that made us stronger?', 'lockin', 'squad', 'hard', true),
('What''s your favorite thing about how we handle disagreements?', 'lockin', 'squad', 'hard', true),
('What''s something you''ve learned about yourself through our friendship?', 'lockin', 'squad', 'hard', true),
('What''s a way you''ve helped one of us through a tough time?', 'lockin', 'squad', 'hard', true),
('What''s something you''re grateful for about our friendship that you don''t usually say?', 'lockin', 'squad', 'hard', true),
('What''s a challenge we''ve overcome together that made us stronger?', 'lockin', 'squad', 'hard', true),
('What''s your favorite thing about how we handle disagreements?', 'lockin', 'squad', 'hard', true),
('What''s something you''ve learned about yourself through our friendship?', 'lockin', 'squad', 'hard', true),
('What''s a way you''ve helped one of us through a tough time?', 'lockin', 'squad', 'hard', true),
('What''s something you''re grateful for about our friendship that you don''t usually say?', 'lockin', 'squad', 'hard', true),
('What''s a challenge we''ve overcome together that made us stronger?', 'lockin', 'squad', 'hard', true),
('What''s your favorite thing about how we handle disagreements?', 'lockin', 'squad', 'hard', true),
('What''s something you''ve learned about yourself through our friendship?', 'lockin', 'squad', 'hard', true),
('What''s a way you''ve helped one of us through a tough time?', 'lockin', 'squad', 'hard', true),
('What''s something you''re grateful for about our friendship that you don''t usually say?', 'lockin', 'squad', 'hard', true),
('What''s a challenge we''ve overcome together that made us stronger?', 'lockin', 'squad', 'hard', true),
('What''s your favorite thing about how we handle disagreements?', 'lockin', 'squad', 'hard', true),

-- Premium Ride-or-Die Prompts (112 prompts)
-- Ride-or-Die Spark Premium (37 prompts)
('What''s the moment you knew you wanted to spend the rest of your life with me?', 'spark', 'ride-or-die', 'easy', true),
('If you could change one thing about how we handle conflict, what would it be?', 'spark', 'ride-or-die', 'medium', true),
('What''s the biggest fear you have about our future together?', 'spark', 'ride-or-die', 'hard', true),
('If we had to describe our love in three words, what would yours be?', 'spark', 'ride-or-die', 'medium', true),
('What''s the deepest truth about yourself that you''ve never shared with anyone?', 'spark', 'ride-or-die', 'hard', true),
('What''s a quirky habit of mine you secretly love?', 'spark', 'ride-or-die', 'easy', true),
('What''s something about me that surprised you when we first met?', 'spark', 'ride-or-die', 'easy', true),
('What''s a small thing I do that makes you smile?', 'spark', 'ride-or-die', 'easy', true),
('What''s something you''ve learned about yourself since we''ve been together?', 'spark', 'ride-or-die', 'easy', true),
('What''s a memory of us that you think about often?', 'spark', 'ride-or-die', 'easy', true),
('What''s something you''re curious about my past that you''ve never asked?', 'spark', 'ride-or-die', 'easy', true),
('What''s a way I make you feel most loved?', 'spark', 'ride-or-die', 'easy', true),
('What''s something you''ve always wanted to tell me but haven''t found the right moment?', 'spark', 'ride-or-die', 'easy', true),
('What''s a dream you have for us that you haven''t shared yet?', 'spark', 'ride-or-die', 'easy', true),
('What''s something about our relationship that makes you feel most secure?', 'spark', 'ride-or-die', 'easy', true),
('What''s a way you show love or care that you think I might not notice?', 'spark', 'ride-or-die', 'easy', true),
('What''s something you''re working on improving about yourself right now?', 'spark', 'ride-or-die', 'easy', true),
('What''s a quality you admire in others that you wish you had more of?', 'spark', 'ride-or-die', 'easy', true),
('What''s something you''re grateful for that you don''t usually talk about?', 'spark', 'ride-or-die', 'easy', true),
('What''s a childhood memory that shaped who you are today?', 'spark', 'ride-or-die', 'easy', true),
('What''s something you''re secretly really good at that might surprise me?', 'spark', 'ride-or-die', 'easy', true),
('What''s a fear or insecurity you have that you haven''t shared with me?', 'spark', 'ride-or-die', 'easy', true),
('What''s something you''ve always wanted to try but never had the courage to do?', 'spark', 'ride-or-die', 'easy', true),
('What''s a belief or value that''s really important to you that I might not know about?', 'spark', 'ride-or-die', 'easy', true),
('What''s something you''re proud of that you''ve never told me about?', 'spark', 'ride-or-die', 'easy', true),
('What''s a way you''ve changed or grown recently that you want me to notice?', 'spark', 'ride-or-die', 'easy', true),
('What''s something you''re curious about me that you''ve never asked?', 'spark', 'ride-or-die', 'easy', true),
('What''s a dream or goal you have that you haven''t shared with me yet?', 'spark', 'ride-or-die', 'easy', true),
('What''s something you wish you could tell your past self about relationships?', 'spark', 'ride-or-die', 'easy', true),
('What''s a way you show love or care that you think I might not notice?', 'spark', 'ride-or-die', 'easy', true),
('What''s something you''re working on improving about yourself right now?', 'spark', 'ride-or-die', 'easy', true),
('What''s a quality you admire in others that you wish you had more of?', 'spark', 'ride-or-die', 'easy', true),
('What''s something you''re grateful for that you don''t usually talk about?', 'spark', 'ride-or-die', 'easy', true),
('What''s a childhood memory that shaped who you are today?', 'spark', 'ride-or-die', 'easy', true),
('What''s something you''re secretly really good at that might surprise me?', 'spark', 'ride-or-die', 'easy', true),
('What''s a fear or insecurity you have that you haven''t shared with me?', 'spark', 'ride-or-die', 'easy', true),
('What''s something you''ve always wanted to try but never had the courage to do?', 'spark', 'ride-or-die', 'easy', true),

-- Ride-or-Die Vibe Premium (37 prompts)
('What''s the most vulnerable thing you''ve shared with me?', 'vibe', 'ride-or-die', 'hard', true),
('What''s your love language and how do you show it?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something about me that surprised you when we first met?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a way I make you feel most loved?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something you''ve learned about yourself through our relationship?', 'vibe', 'ride-or-die', 'medium', true),
('What''s your favorite memory of us together?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something you''ve always wanted to tell me but haven''t?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a small habit of mine that makes you smile?', 'vibe', 'ride-or-die', 'medium', true),
('If we could swap one daily routine, what would you want to try from my life?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a challenge we''ve overcome together that made us stronger?', 'vibe', 'ride-or-die', 'medium', true),
('What''s your favorite thing about how we handle disagreements?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something you''ve learned about yourself through our relationship?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a way I''ve helped you heal from past wounds?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something about our relationship that scares you?', 'vibe', 'ride-or-die', 'medium', true),
('What''s the most important thing you''ve learned about love from being with me?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a way you''ve changed because of our relationship?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something you''re grateful for about our relationship that you don''t usually say?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a challenge we''ve overcome together that made us stronger?', 'vibe', 'ride-or-die', 'medium', true),
('What''s your favorite thing about how we handle disagreements?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something you''ve learned about yourself through our relationship?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a way I''ve helped you heal from past wounds?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something about our relationship that scares you?', 'vibe', 'ride-or-die', 'medium', true),
('What''s the most important thing you''ve learned about love from being with me?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a way you''ve changed because of our relationship?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something you''re grateful for about our relationship that you don''t usually say?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a challenge we''ve overcome together that made us stronger?', 'vibe', 'ride-or-die', 'medium', true),
('What''s your favorite thing about how we handle disagreements?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something you''ve learned about yourself through our relationship?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a way I''ve helped you heal from past wounds?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something about our relationship that scares you?', 'vibe', 'ride-or-die', 'medium', true),
('What''s the most important thing you''ve learned about love from being with me?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a way you''ve changed because of our relationship?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something you''re grateful for about our relationship that you don''t usually say?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a challenge we''ve overcome together that made us stronger?', 'vibe', 'ride-or-die', 'medium', true),
('What''s your favorite thing about how we handle disagreements?', 'vibe', 'ride-or-die', 'medium', true),
('What''s something you''ve learned about yourself through our relationship?', 'vibe', 'ride-or-die', 'medium', true),
('What''s a way I''ve helped you heal from past wounds?', 'vibe', 'ride-or-die', 'medium', true),

-- Ride-or-Die Lock-In Premium (37 prompts)
('What''s our biggest shared dream?', 'lockin', 'ride-or-die', 'hard', true),
('What''s the most vulnerable thing you''ve ever shared with me?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something you want to change about our relationship?', 'lockin', 'ride-or-die', 'hard', true),
('What''s your deepest fear about our future together?', 'lockin', 'ride-or-die', 'hard', true),
('What''s the most important lesson you''ve learned from our relationship?', 'lockin', 'ride-or-die', 'hard', true),
('What''s your vision for our life together in 10 years?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something you''d never want to lose about our connection?', 'lockin', 'ride-or-die', 'hard', true),
('What''s the hardest thing you''ve had to forgive me for?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a dream we''ve never shared that could change our future together?', 'lockin', 'ride-or-die', 'hard', true),
('What''s the most difficult conversation we''ve ever had and what did it teach us?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a way I''ve helped you heal from past wounds?', 'lockin', 'ride-or-die', 'hard', true),
('What''s your deepest insecurity and how can I help you overcome it?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something about our relationship that scares you?', 'lockin', 'ride-or-die', 'hard', true),
('What''s the most important thing you''ve learned about love from being with me?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a way you''ve changed because of our relationship?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something you''re grateful for about our relationship that you don''t usually say?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a challenge we''ve overcome together that made us stronger?', 'lockin', 'ride-or-die', 'hard', true),
('What''s your favorite thing about how we handle disagreements?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something you''ve learned about yourself through our relationship?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a way I''ve helped you heal from past wounds?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something about our relationship that scares you?', 'lockin', 'ride-or-die', 'hard', true),
('What''s the most important thing you''ve learned about love from being with me?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a way you''ve changed because of our relationship?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something you''re grateful for about our relationship that you don''t usually say?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a challenge we''ve overcome together that made us stronger?', 'lockin', 'ride-or-die', 'hard', true),
('What''s your favorite thing about how we handle disagreements?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something you''ve learned about yourself through our relationship?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a way I''ve helped you heal from past wounds?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something about our relationship that scares you?', 'lockin', 'ride-or-die', 'hard', true),
('What''s the most important thing you''ve learned about love from being with me?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a way you''ve changed because of our relationship?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something you''re grateful for about our relationship that you don''t usually say?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a challenge we''ve overcome together that made us stronger?', 'lockin', 'ride-or-die', 'hard', true),
('What''s your favorite thing about how we handle disagreements?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something you''ve learned about yourself through our relationship?', 'lockin', 'ride-or-die', 'hard', true),
('What''s a way I''ve helped you heal from past wounds?', 'lockin', 'ride-or-die', 'hard', true),
('What''s something about our relationship that scares you?', 'lockin', 'ride-or-die', 'hard', true),

-- Additional premium prompt to make 335 total
('What''s the most important thing you''ve learned about love from being with me?', 'lockin', 'ride-or-die', 'hard', true);
